### ISSUE TITLE
Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by yongjie0203** [StarkShang/vite-plugin-chrome-extension#23]
Cannot read property 'reduce' of undefined
error during build:
TypeError: Cannot read property 'reduce' of undefined
    at /home/vite/chrome-extend-fastautobuy/node_modules/vite-plugin-chrome-extension/lib/index-cjs.js:1989:43
    at Array.reduce (<anonymous>)
    at deriveFiles (/home/vite/chrome-extend-fastautobuy/node_modules/vite-plugin-chrome-extension/lib/index-cjs.js:1988:7)
    at ManifestProcessor.resolveInput (/home/vite/chrome-extend-fastautobuy/node_modules/vite-plugin-chrome-extension/lib/index-cjs.js:2659:48)
    at Object.options (/home/vite/chrome-extend-fastautobuy/node_modules/vite-plugin-chrome-extension/lib/index-cjs.js:3237:51)
    at /home/yongjie/vite/chrome-extend-fastautobuy/node_modules/rollup/dist/shared/rollup.js:23473:43
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getInputOptions (/home/vite/chrome-extend-fastautobuy/node_modules/rollup/dist/shared/rollup.js:23466:61)
    at async rollupInternal (/home/vite/chrome-extend-fastautobuy/node_modules/rollup/dist/shared/rollup.js:23413:72)
    at async doBuild (/home/vite/chrome-extend-fastautobuy/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43134:24)
vite@ubuntu:~/vite/chrome-extend-fastautobuy$

**Comment by mukul-mehta** [comment]
@yongjie0203 I happen to have the same issue, what was the fix in your case?

**Comment by 0leg53** [comment]
> @yongjie0203 I happen to have the same issue, what was the fix in your case?

In my case it was something wrong with `web_accessible_resources` values in `manifest.json` file  
please check it out https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/
